# Generated by Django 4.2.1 on 2023-06-22 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_home_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
