# Generated by Django 4.2.1 on 2023-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateLimit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratelimitinfo',
            name='suspended',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
