# Generated by Django 4.2.1 on 2023-12-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RateLimit', '0003_alter_ratelimitinfo_suspended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratelimitinfo',
            old_name='suspended',
            new_name='suspended_time',
        ),
    ]
