# Generated by Django 4.2.1 on 2023-06-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user_id',
            new_name='parent_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='with_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
