# Generated by Django 4.2.1 on 2023-06-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0002_rename_user_id_chat_parent_id_chat_with_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='with_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='users_id',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
