# Generated by Django 4.2.1 on 2023-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0003_remove_chat_parent_id_remove_chat_with_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='users_id',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
