# Generated by Django 4.2.1 on 2023-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0004_alter_chat_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
