# Generated by Django 4.2.1 on 2023-07-24 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0005_alter_messages_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
