# Generated by Django 4.2.1 on 2023-07-24 16:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0006_remove_chat_users_id_chat_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chats',
        ),
    ]
