# Generated by Django 4.2.1 on 2023-07-24 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0007_rename_chat_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
