# Generated by Django 4.2.1 on 2023-07-24 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Chats', '0008_remove_messages_parent_id_messages_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
