# Generated by Django 4.2.1 on 2023-11-30 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0009_alter_messages_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
