# Generated by Django 4.2.1 on 2023-05-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuarios_current_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together={('first_names', 'last_names')},
        ),
    ]
