# Generated by Django 4.2.1 on 2023-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
