# Generated by Django 4.2.1 on 2023-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_usuarios_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
