# Generated by Django 4.2.1 on 2023-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_usuarios_activation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='activation_code',
            field=models.CharField(max_length=6),
        ),
    ]
