# Generated by Django 4.2.1 on 2023-06-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0001_initial'),
        ('Usuarios', '0010_alter_usuarios_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='chats',
            field=models.ManyToManyField(to='Chats.chat'),
        ),
    ]
