# Generated by Django 4.2.1 on 2023-06-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_usuarios_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='chats',
        ),
    ]
