# Generated by Django 4.2.1 on 2023-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0007_delete_notificationslist'),
        ('Usuarios', '0012_remove_usuarios_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='notifications',
            field=models.ManyToManyField(to='Notifications.notifications'),
        ),
    ]
