# Generated by Django 4.2.1 on 2023-06-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_alter_usuarios_notifications_alter_usuarios_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='current_status',
        ),
    ]
