# Generated by Django 4.2.1 on 2023-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0015_remove_usuarios_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='first_names',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_names',
            field=models.CharField(max_length=30),
        ),
    ]
