# Generated by Django 4.2.1 on 2023-06-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0016_alter_usuarios_first_names_alter_usuarios_last_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='photo',
            field=models.CharField(max_length=30),
        ),
    ]
