# Generated by Django 4.2.1 on 2023-06-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0017_alter_usuarios_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='activation_code',
        ),
    ]
