# Generated by Django 4.2.1 on 2023-06-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0018_remove_usuarios_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='photo',
            new_name='photo_link',
        ),
    ]
