# Generated by Django 4.2.1 on 2023-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0026_alter_usuarios_photo_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='first_names',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_names',
        ),
    ]
