# Generated by Django 4.2.1 on 2023-09-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0027_remove_usuarios_age_remove_usuarios_first_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='is_online',
        ),
    ]
