# Generated by Django 4.2.1 on 2024-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0028_remove_usuarios_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
