# Generated by Django 4.2.1 on 2024-02-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0029_usuarios_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='code',
            new_name='security_code',
        ),
    ]
