# Generated by Django 4.2.1 on 2024-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0030_rename_code_usuarios_security_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
