# Generated by Django 4.2.1 on 2023-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0005_alter_notifications_receive_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='receive_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
