# Generated by Django 4.2.1 on 2023-06-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0006_alter_notifications_receive_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationsList',
        ),
    ]
