# Generated by Django 4.2.1 on 2023-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0010_remove_notifications_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sender_user_id',
            field=models.SmallIntegerField(),
        ),
    ]
